### ISSUE TITLE
heartbeat url is not working if i have my application url https on consul

### ISSUE THREAD

**Issue by athishsreeram** [codecentric/spring-boot-admin#1186]
heartbeat url is not working if i have my application url https url

In consul am able to see the health check working on the Consul
This the register to the consul
```
{
"ID": "api",
"Name": "api",
"Service": "api",
"Tags": [
"management.context-path=/api/v1",
"management.server.ssl.enabled=true"
],
"Meta": {},
"Port": 80,
"Address": "10.222.222.22",
"Weights": {
"Passing": 1,
"Warning": 1
},
"EnableTagOverride": false,
"check":{
"ID": "api",
"Name": "HTTP Health Check",
"HTTP": "https://10.222.222.22:80/api/v1/health",
"Method": "GET",
"Header": {"x-foo":["bar", "baz"]},
"Interval": "10s",
"TLSSkipVerify": true
}
}
```

how to make the heartbeat url to be https instead of http ?

@joshiste Can you help ?

I see issue fixed for http url 
https://github.com/codecentric/spring-boot-admin/issues/1092

**Comment by athishsreeram** [comment]
heartbeat url is not working if i have my application url https url

In consul am able to see the health check working on the Consul
This the register to the consul
{
"ID": "api",
"Name": "api",
"Service": "api",
"Tags": [
"management.context-path=/api/v1"
],
"Meta": {},
"Port": 80,
"Address": "10.222.222.22",
"Weights": {
"Passing": 1,
"Warning": 1
},
"EnableTagOverride": false,
"check":{
"ID": "api",
"Name": "HTTP Health Check",
"HTTP": "https://10.222.222.22:80/api/v1/health",
"Method": "GET",
"Header": {"x-foo":["bar", "baz"]},
"Interval": "10s",
"TLSSkipVerify": true
}
}

how to make the heartbeat url to be https instead of http ?

@joshiste Can you help ?

**Comment by Rugal** [comment]
Hi,

I am having the same issue right now. Basically, my service is able to register to the Consul, an Consul could see my service for sure. But SBA is only picking up the HTTP. 

Do you have a direct of where we should fix the problem at? I would like to fix that myself and create PR.

Thank you

**Comment by joshiste** [comment]
Looks like a duplicate of https://github.com/codecentric/spring-boot-admin/issues/737#issuecomment-388627104 (solution also included)

**Comment by athishsreeram** [comment]
<img width="1677" alt="Screen Shot 2019-07-02 at 11 51 50 AM" src="https://user-images.githubusercontent.com/29419776/60527945-51697e00-9cc1-11e9-9435-13340867f796.png">

Please find the screen shot issue persist even following your recommendation.

**Comment by athishsreeram** [comment]
@joshiste please look into this if this configuration works i dont find any documentation for this clear in Spring Boot admin with respect to consul. Eureka has some documentations on this aspect currently. Can you please reopen this issue.

**Comment by joshiste** [comment]
you must not set the discovery scheme to the metadata but for the application.properties of the SBA server (so that it's discovery client get configured)

**Comment by athishsreeram** [comment]
It doesn't work i tried to add the property you mentioned but it just makes the SBA url as https in the dashboard. Not all the other API Client application url is getting changed to https. 

Does SBA support for the scheme change through spring.cloud.consul.discovery.tags configuration ?

**Comment by keyone** [comment]
Can you please reopen this ticket

**Comment by Ashish1270** [comment]
any solution for this issue?....i'm facing the same

**Comment by Ashish1270** [comment]
> Have you got any solution for this?

**Comment by SteKoe** [comment]
Hi @Ashish1270, we have tried to reproduce the behavior and solved it by setting the mentioned property `spring.cloud.consul.discovery.scheme=https` in the client application registered to Consul. In our test project, there was no need to reconfigure SBA. Please check whether your clients have set the property mentioned before to `https`.

**Comment by ashish-c-sharma-db** [comment]
@SteKoe : I tried it but still facing the same problem. I think the problem is with my current spring boot version. When I upgrade spring boot it starts working. Previous version of spring boot is 2.1.0

**Comment by Ashish1270** [comment]
@SteKoe we have this property already in our config. It looks like our application is running on older springboot version(2.1.8-RELEASE) and our spring boot admin is running on SB version 2.6.6. Newer version is expecting secure=true in metadata and application does not support metadata. Do we need to upgrade our SB version or is there any other solution to resolve this?
