### ISSUE TITLE
Using Hazelcast as cluster client won't update event log

### ISSUE THREAD

**Issue by lukasz-kaminski** [codecentric/spring-boot-admin#1429]
We're running Spring Boot Admin as a single instance in Kubernetes. Because of this, it's prone to restarts, so we need to keep the event log outside of the application. We want to use Hazelcast for this, but we've encountered an error.

We have Hazelcast cluster running in our infrastructure and we're allowed to use it **as clients only**. The documentation and examples show creating/joining the cluster as a member which we cannot do. Hence, our `build.gradle` has the following entry:

```groovy
implementation 'com.hazelcast:hazelcast-client'
```

and our config:

```java
@Bean
public ClientConfig hcConfig(@Value("${spring.boot.admin.hazelcast-address}") String hazelcastAddress) {
    ClientConfig clientConfig = new ClientConfig();
    clientConfig.getNetworkConfig().addAddress(hazelcastAddress);
    return clientConfig;
}
```

And this works. The application connects to the cluster, creates the maps, populates them with new instances, and after a restart it reads the state fine. There are two problems, though.

1. All applications have status `UNKNOWN`
![image](https://user-images.githubusercontent.com/11961746/81948032-8ba1ec80-9601-11ea-866d-442c101e1974.png)

2. SBA can't update the event log. Whenever any application deregisters the logs get spammed with logs like this:

```
d.c.b.a.s.e.ConcurrentMapEventStore      : Unsuccessful attempt append the events [InstanceDeregisteredEvent(super=InstanceEvent(instance=98a33ba0a679, version=1, timestamp=2020-05-14T13:01:27.545406Z, type=DEREGISTERED))]
```

This happens because `eventLog.replace(id, oldEvents, newEvents)` always returns false. Debugging has proven that `oldEvents` contents match what `eventLog.get(id)` returns. Additionally calling `replace` on a list of `String`s worked fine. This might indicate that event lists are not compared properly by Hazelcast, but I don't have much experience with Hazelcast.

Java version: 11
SBA version: 2.2.3
Spring Boot version: 2.2.7.RELEASE
Hazelcast version: 3.10.6

**Comment by joshiste** [comment]
do you have a project for me to reproduce the issue?

**Comment by lukasz-kaminski** [comment]
I should be able to provide it on Monday if that's ok.

**Comment by lukasz-kaminski** [comment]
@joshiste Please look at this repo: https://github.com/Bisnode/sba-hazel-issue

**Comment by lukasz-kaminski** [comment]
Hey @joshiste, have you had the chance to try it out? Let me know if I can help.

**Comment by joshiste** [comment]
sorry. Didn't found the time...

**Comment by srempfer** [comment]
I added some tests for further analysis based on the 2.2.x branch (see above linked commit)
With the test `de.codecentric.boot.admin.server.HazelcastMapIssue1429IntegrationTest#verifyRegistrationAfterRestart` I was able to reproduce the problem.

Unfortunately with the much more simpler test `de.codecentric.boot.admin.server.HazelcastMapIssue1429Test#verifyReplaceWithNoneEmptyEventLog` I was not able to reproduce problem.

Hint: To run the test you need Docker.
Perhaps this helps to get the root cause of the problem.

Here some link I found during my research:
* https://github.com/hazelcast/hazelcast/pull/12388/files
* https://github.com/hazelcast/hazelcast/pull/12388
* https://github.com/hazelcast/hazelcast/issues/12574

**Comment by srempfer** [comment]
Update:

Now I could reproduce the problem also with the test `de.codecentric.boot.admin.server.HazelcastMapIssue1429Test#verifyReplaceWithNoneEmptyEventLogWithMetadata`.

The metadata of a Registration causing the strange behavior.

**Comment by srempfer** [comment]
Update:
The problem in a special combination when a list of objects that have a map attribute using Lombock Builders to fill the map.

See example object `de.codecentric.boot.admin.server.HazelcastMapIssue1429Registration` and the involved test `de.codecentric.boot.admin.server.HazelcastMapIssue1429Test#verifyReplaceWithListOfTestRegistrationWithMetadata` / `de.codecentric.boot.admin.server.HazelcastMapIssue1429Test#verifyReplaceWithListOfTestRegistrationWithMetadataBuilderStyle`

**Comment by srempfer** [comment]
This issue https://github.com/hazelcast/hazelcast/issues/12574 should fix the problem. 

Unfortunately it's only included in the big major release 4.x from Hazelcast.
In addition the new version is not yet out of the box supported in the current Spring Boot version - see https://github.com/spring-projects/spring-boot/issues/20856

The only solution that came in my mind is a Work-A-Round like this

```
// ------------ Orginal ---------------------- //
this.metadata = new LinkedHashMap<>(metadata);
// ------------- WORK-A-ROUND ---------------- //
//this.metadata = new LinkedHashMap<>();
//this.metadata.forEach((key, value) -> metadata.put(key, value));
// -------------------------------------------//
```

**Comment by lukasz-kaminski** [comment]
Impressive work @srempfer! The workaround is not pretty but it might be the only way. However, maybe we can use serializer from the Hazelcast issue you've linked and add them client side as [SerializerConfig](https://docs.hazelcast.org/docs/clients/java/3.6.1/com/hazelcast/config/SerializerConfig.html)?
I'm not sure if it would work that way, though.

**Comment by joshiste** [comment]
@srempfer thanks for digging deep into this!

**Comment by nickcaballero** [comment]
Spring Boot 2.4.0 is expected to go out on November 12, which has support for Hazelcast 4. Maybe upgrading Hazelcast version is the way to go here?

**Comment by lukasz-kaminski** [comment]
@nickcaballero it will probably fix the issue. However, Hazelcast I'm using won't be upgraded anytime soon, so this doesn't fix my problem and I might not be the only one :)

**Comment by srempfer** [comment]
@joshiste: Should I add the above mentioned workaround?

**Comment by joshiste** [comment]
@srempfer if it solves the problem, please go ahead.
