### ISSUE TITLE
logfile viewer 416

### ISSUE THREAD

**Issue by vpodoprigo** [codecentric/spring-boot-admin#2011]
Spring Boot version 2.6.3
Spring Boot Admin version 2.6.2
Looks like it is related to https://github.com/codecentric/spring-boot-admin/issues/1632

Look like It is not fixed enough 
1) logs not loaded at all
![изображение](https://user-images.githubusercontent.com/99340454/161490799-2e7abd02-244d-4fae-9e1f-843a29b3e2cd.png)
And logs are opened in case if open it in new tab

2)logs are loaded but there is error requests spam
![изображение](https://user-images.githubusercontent.com/99340454/161491397-91179471-12ee-40ee-ae1a-ab520abea3d2.png)
![изображение](https://user-images.githubusercontent.com/99340454/161491705-ebf6ff0b-61ee-4f49-a126-ab02158d2558.png)

**Comment by vpodoprigo** [comment]
I always happens after rolling over of logs

**Comment by erikpetzold** [comment]
Hi @vpodoprigo 

the 1. point looks like a bug, we will have a look. If you can provide any more details please add them as comment.

The 2. point is expected behaviour I would say. The client (browser) does not know when the files are rolled over. It is just polling for the next batch. So it needs the error response to know there is nothing more to load (because of rollover). Then it can start at the beginning of the file again.

**Comment by vpodoprigo** [comment]
Hi @erikpetzold. 2) I agree if it happpens once but it goes to loop.
![изображение](https://user-images.githubusercontent.com/99340454/162391497-82074065-96a3-4d4c-8190-30ad2913c319.png)

according to the commit i see that next lines where removed:

` // Reload the last byte to avoid a 416: Range unsatisfiable.
        // If the response has length = 1 the file hasn't beent changed.
        // If the response status is 416 the logfile has been truncated.
        range = `bytes=${size - 1}-`;
`
I suppose it is the reason for point 2

**Comment by vpodoprigo** [comment]
for the 1 point:
after the roll over i see request with `range: bytes= -307200`. it works if there was not rollover but it doesnt work after the first roll over. i dont know reason...

**Comment by vpodoprigo** [comment]
Additionally to 1): i did experiment via postman. 
I did the same request as spring boot admin does directly to instance and it works. (url /actuator/logfile range: bytes= -307200)
But it doesn't work if i use spring boot admin endpoint proxy. (url /admin/instances/fd062a9e417f/actuator/logfile range: bytes= -307200)

So i suppose there is problem inside spring boot admin server proxy endpoints

**Comment by ulischulte** [comment]
Hi @vpodoprigo ,
I assume you are using the servlet variant of Spring Boot Admin, since this is the only way I was able to reproduce the bug in an older version of SBA.
 
1) This issue should have been fixed with #1632 . Could you please try the newest version of Spring Boot Admin and retest?
2) This should be the expected behaviour after the fix (rolling file bug). Could you provide a sample project which reproduces your bug? We assume the issue could be connected to a logfile configuration we haven't addressed in our observations so far.
I only was able to reproduce a 416 status code with each request with a logback config including a very small max-file-size (`logging.logback.rollingpolicy.max-file-size`). So in my case, the logfile was rolling over after each request which resulted in a new successful request with a 206 state including the content of the newly created file.

However, there still seems to be a bug with the reactive variant of Spring Boot Admin which uses webflux. The endpoint 'actuator/logfile' is returning a BAD_REQUEST status while watching the Logfile view in case of a rolling logfile. This results in the same bug described in 1) -> The Logfile view stops updating. We will fix this issue in a future version.

**Comment by vpodoprigo** [comment]
Hi @ulischulte . There is the same issue with latest version.
I use the servlet variant of Spring Boot Admin with Eureka Server packed inside.
Also tried version where the next code is not removed and it works for point 2)

```
        // Reload the last byte to avoid a 416: Range unsatisfiable.
        // If the response has length = 1 the file hasn't beent changed.
        // If the response status is 416 the logfile has been truncated.
        range = `bytes=${size - 1}-`;
```
But I still have issue with 1) in any version(for old version i at least have button "Dowload log file" for latest i dont have ever this button).

**Comment by vpodoprigo** [comment]
@erikpetzold 
No. Rollover is the default configuration for file appender in spring boot
You can find default config here:
\.m2\repository\org\springframework\boot\spring-boot\2.6.3\spring-boot-2.6.3.jar!\org\springframework\boot\logging\logback\file-appender.xml

**Comment by woodforda** [comment]
Not sure if related but I have an issue with logfile view on 3.0.0.M4 - the page appears blank, however, if you generate enough log entries it starts to appear but at the top of the page (thru page header etc).

**Comment by SteKoe** [comment]
Closed due to inactivity. Feel free to reopen if issue still exists.
