### ISSUE TITLE
Support Internet Explorer 11 / Edge

### ISSUE THREAD

**Issue by gunnarvelle** [codecentric/spring-boot-admin#280]
Viewing admin ui in IE or Edge triggers error 'EventSource' is undefined in all-modules..js.

According to [this Stackoverflow question](http://stackoverflow.com/questions/24498141/is-there-a-microsoft-equivalent-for-html5-server-sent-events) you can use a polyfill to emulate the functionality in IE/Edge.

Could you try to add this polyfill to the project?

Regards
Gunnar Velle

**Comment by joshiste** [comment]
Please try a 1.4.3-SNAPSHOT. Additional to the SSE polyfill one for es6 was necessary.

**Comment by gunnarvelle** [comment]
With the last snapshot the applications show up as expected. But memory-graphs for the applicatons is not rendered in IE 11. Egde is OK.

![image](https://cloud.githubusercontent.com/assets/8956884/19428466/9ecd70fc-944a-11e6-9212-1a62023b37c9.png)

**Comment by joshiste** [comment]
@gunnarvelle I've fixed this. Please have a look at the latest snapshot, which is currently built.

**Comment by gunnarvelle** [comment]
Works like a charm!

------ Original Message ------

**Comment by rantrain** [comment]
I see this issue in version 2.1.4 as well.

**Comment by sildvauresberg** [comment]
Still see this with `spring-boot-admin 2.2.1` and `Microsoft Edge 44.18362.449.0`
